//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassScheduleShadow
    {
        public int ID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ClassRoomID { get; set; }
        public int WhoDeletedID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> TeacherID { get; set; }
    }
}
