//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Degree { get; set; }
        public string Teacher { get; set; }
        public Nullable<bool> Closed { get; set; }
    }
}
