//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkList
    {
        public int ID { get; set; }
        public string Course { get; set; }
        public string Student { get; set; }
        public byte Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Teacher { get; set; }
        public string Degree { get; set; }
    }
}
