//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher1
    {
        public int Person_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Teacher_ID { get; set; }
        public string Degree { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Dismiss { get; set; }
    }
}
